language: node_js
node_js:
- 12
cache:
  yarn: true
  directories:
  - node_modules
env:
  matrix:
  - CI=true
  global:
  - secure: rHCuPDk1HKN+IrhbcPPSSa9JHhgqMaVKqgWN0mgLHuCyVmJ/PPgDtlkF1UZcdHEXoAkzFWEHIjNKPY8nnh8eucELfm3yondGy2xPrJNrNywqnuMI5xmLc3llkWuPJ5GT41r10qJm3Tr7pHyJkSiVIFrZK8YfGhiUbn98+o3xfK44yuLlNijSO7yOOO+Go9M57W3sMfgzL4WCmM8WuTs3eFyYa2tJGRANQMk0etR4YQ2/oTWIKN+sQfMGhC0ueuKY4bx5LqnGuTOv+AmOsK7+9zHn0R3XcV34gn/lzez6gEjGM66f5wYsAaLoFLxSfsSNyWvwCxukFBaboJXqtdjwZLx1/zEABgsg47ovH/cRb3DvFS7Ne/cNv/0dvY3MU5j7R9oUBbbJPKbROtc3oH9rXziM9KInIy31RKH2CMKrQupbjQw4jLThh72tDK+Lp5h4M4pGjGpYjW3ofbI4TTJKjx9ejTg/mbDOY1sm64SEMGKifCVsLQNE9X6VA7wVoUGXliRtGUn3oHVpZ0D/IV3SLpEkF9ykJ04pBalDZdTN8ZxSUKMJQo07hbiE9ju8DP2lc7cnqZPQzFvmPQgP5GDNP5BpT+HFFdTLUcvb+QQvmMqmswsDUcn9WeRL93KizALpZB0TLy/RaAOxJFE5IyuSuwslnih6wLmVtyTFyn/lWt0=
  - secure: hEdsr2VjxMweZkGld/e3orH/5zHYsyXZnQ/DXjtQ/5Zbr4PBjfvrhNn9xd4HZ0LLaHz6ZtRoYHlv3wV83FdXm4AeYCdp5IdwR0+0L0+FsbcBGLFkM9E5RC+Xekg8pCx1aSEhpvPbrQQpd74DhOE3l9PHZEMFJhxw4x28G9zaURkeEK03StHEWg0M6Gdg8mJNi+4CwadERJGI/i1IWPigrmL+/GyxxHqNK0vNr26cpK/IrmxUjdJhBv0tA8A/S037gIP3Timr+ezuNXtKbcpL5PpeXyovIgOkfQxY5KXbYARnx0l36G0p2jG5fnBBC6Aq42qLC2FnZEGDS9T4f/OFZP8ayNFudlF7G9aKYN1Aqy3y9z8D7UyP4KIbt3sjzuERAgsvBs1EtlzSYulA/Lu2cyUiAgbLSpxiFWzVMXq5djixKoPFBvvFm8N3cQ7vQq9341GBN89rT2XoXROXU45iT843DbwTRA1y5AKKOcaapoxy4bZ7Nxo8DTx47JU6IKiV8C7ZlwticDCBk8ZTYjQiAqgJqinGNlJ7LXTHY+QTKiEpE3Gmi7PYW7T2Zq5x8J2zpJMLgPaYJ3BLqoY/veCfKuWmYDcYUeS2YoV6bNLlgQA7j4f7tq3W5ibJ5JVEzPoQ/KAlnsRtOpcJzfIQ7pTvZOcu0lsYHiDHsY0YMPP2tKI=
jobs:
  include:
  - stage: Tests
  - name: Unit Test Execution
    script: yarn test
  - stage: deployment
    name: Deploy artifacts to Netlify
    before_deploy:
    - yarn build
    - npm install netlify-cli -g
    deploy:
      provider: netlify
      site: $NETLIFY_SITE_ID
      auth: $NETLIFY_ACCESS_TOKEN
      edge: true
      prod: true
      dir: ./build
      message: Netlify Deployment Started
      skip_cleanup: true
      on:
        branch: master
