export const NEWS_FEED_MOCK = {
    hits: [
        {
            "id": 22765801,
            "title": "Dear Jeff Bezos, instead of firing me, protect your workers from coronavirus",
            "points": 3,
            "user": "sahin-boydas",
            "created_at_i": 1585880103,
            "time_ago": "5 minutes ago",
            "comments_count": 24,
            "type": "link",
            "url": "https://www.theguardian.com/commentisfree/2020/apr/02/dear-jeff-bezos-amazon-instead-of-firing-me-protect-your-workers-from-coronavirus",
            "domain": "theguardian.com"
        },
        {
            "id": 22765799,
            "title": "Doctors urged to recognize post-antidepressant sexual dysfunction",
            "points": 2,
            "user": "sweetmountain",
            "created_at_i": 1585880067,
            "time_ago": "6 minutes ago",
            "comments_count": 65,
            "type": "link",
            "url": "https://www.eurekalert.org/pub_releases/2020-01/s-dut012320.php",
            "domain": "eurekalert.org"
        },
        {
            "id": 22765780,
            "title": "Show HN: Log-Scale COVID19 Plots",
            "points": 1,
            "user": "6b6b64",
            "created_at_i": 1585879793,
            "time_ago": "10 minutes ago",
            "comments_count": 12,
            "type": "link",
            "url": "https://bitbucket.org/kkd/covid19_plots",
            "domain": "bitbucket.org"
        },
        {
            "id": 22765769,
            "title": "Ask HN: What data do people/companies pay for in various industries?",
            "points": 1,
            "user": "chirau",
            "created_at_i": 1585879625,
            "time_ago": "13 minutes ago",
            "comments_count": 3,
            "type": "ask",
            "url": "item?id=22765769"
        },
        {
            "id": 22765768,
            "title": "The State of Coronavirus in Japan from an Everyday Citizen’s Perspective",
            "points": 1,
            "user": "TakakiTohno",
            "created_at_i": 1585879623,
            "time_ago": "13 minutes ago",
            "comments_count": 8,
            "type": "link",
            "url": "https://medium.com/in-quarantine/the-state-of-coronavirus-in-japan-from-an-everyday-citizens-perspective-japan-bound-94c0209b3e27",
            "domain": "medium.com"
        },
        {
            "id": 22765766,
            "title": "Python NLP Tutorial: Information Extraction and Knowledge Graphs",
            "points": 1,
            "user": "d99kris",
            "created_at_i": 1585879618,
            "time_ago": "13 minutes ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://medium.com/swlh/python-nlp-tutorial-information-extraction-and-knowledge-graphs-43a2a4c4556c",
            "domain": "medium.com"
        },
        {
            "id": 22765762,
            "title": "I Lost My Husband to Covid-19",
            "points": 2,
            "user": "TakakiTohno",
            "created_at_i": 1585879541,
            "time_ago": "14 minutes ago",
            "comments_count": 1,
            "type": "link",
            "url": "https://medium.com/wake-up-call/i-lost-my-husband-to-covid-19-d6c41240a461",
            "domain": "medium.com"
        },
        {
            "id": 22765741,
            "title": "Governor Inslee extends Washington state stay at home order to May 4",
            "points": 1,
            "user": "georgeoliver",
            "created_at_i": 1585879179,
            "time_ago": "20 minutes ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://www.seattletimes.com/seattle-news/politics/gov-inslee-extends-washington-states-coronavirus-stay-home-order-through-end-of-may-4/",
            "domain": "seattletimes.com"
        },
        {
            "id": 22765728,
            "title": "Marriage Is a Profession in India",
            "points": 1,
            "user": "anassaifi",
            "created_at_i": 1585879032,
            "time_ago": "23 minutes ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://stories197.blogspot.com/2020/04/marriage-is-profession-in-india_1.html",
            "domain": "stories197.blogspot.com"
        },
        {
            "id": 22765723,
            "title": "Making Black Tea from Your Camellia Japonica",
            "points": 2,
            "user": "grawprog",
            "created_at_i": 1585878975,
            "time_ago": "24 minutes ago",
            "comments_count": 105,
            "type": "link",
            "url": "http://pandragonathome.blogspot.com/2009/11/making-black-tea-from-your-camellia.html",
            "domain": "pandragonathome.blogspot.com"
        },
        {
            "id": 22765716,
            "title": "Ask HN: Personal liability releasing an app as a solo dev",
            "points": 2,
            "user": "mindvirus",
            "created_at_i": 1585878860,
            "time_ago": "26 minutes ago",
            "comments_count": 2,
            "type": "ask",
            "url": "item?id=22765716"
        },
        {
            "id": 22765714,
            "title": "Statlogger: Email-based stat tracking and charts",
            "points": 1,
            "user": "oftenwrong",
            "created_at_i": 1585878832,
            "time_ago": "26 minutes ago",
            "comments_count": 9,
            "type": "link",
            "url": "http://www.statlogger.com/",
            "domain": "statlogger.com"
        },
        {
            "id": 22765681,
            "title": "3D Printer Almost Fire",
            "points": 2,
            "user": "luu",
            "created_at_i": 1585878399,
            "time_ago": "33 minutes ago",
            "comments_count": 2,
            "type": "link",
            "url": "https://www.bhencke.com/blog//2016/12/3d-printer-almost-fire.html",
            "domain": "bhencke.com"
        },
        {
            "id": 22765665,
            "title": "US Army Off-Road Nuclear Train",
            "points": 1,
            "user": "stmw",
            "created_at_i": 1585878201,
            "time_ago": "37 minutes ago",
            "comments_count": 5,
            "type": "link",
            "url": "http://ansnuclearcafe.org/2020/03/27/army-off-road-nuclear-train-1958/",
            "domain": "ansnuclearcafe.org"
        },
        {
            "id": 22765663,
            "title": "3D-printing facility in CA stepping in with face shields to fight coronavirus",
            "points": 1,
            "user": "harambae",
            "created_at_i": 1585878157,
            "time_ago": "37 minutes ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://www.cbsnews.com/news/3d-printing-facility-helping-produce-face-shields-in-fight-against-coronavirus/",
            "domain": "cbsnews.com"
        },
        {
            "id": 22765654,
            "title": "An Overview of Dcmtk – The Dicom Toolkit",
            "points": 1,
            "user": "jdgiese",
            "created_at_i": 1585878083,
            "time_ago": "39 minutes ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://innolitics.com/articles/overview-of-DCMTK-the-DICOM-toolkit/",
            "domain": "innolitics.com"
        },
        {
            "id": 22765651,
            "title": "Jack Schofield Has Died",
            "points": 1,
            "user": "sys_64738",
            "created_at_i": 1585878066,
            "time_ago": "39 minutes ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://www.theguardian.com/technology/askjack/2020/apr/02/so-long-and-thanks-for-all-the-fish",
            "domain": "theguardian.com"
        },
        {
            "id": 22765607,
            "title": "US inaction is hurting the chance for peace in Libya",
            "points": 1,
            "user": "jamesdd",
            "created_at_i": 1585877541,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://thehill.com/opinion/international/490917-us-inaction-is-hurting-the-chance-for-peace-in-libya",
            "domain": "thehill.com"
        },
        {
            "id": 22765596,
            "title": "Samsung Galaxy S20 Ultra 5G Review – Android Excellence at a Premium",
            "points": 2,
            "user": "PrimeVinister",
            "created_at_i": 1585877393,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://techstomper.com/samsung-galaxy-s20-ultra-5g-review/",
            "domain": "techstomper.com"
        },
        {
            "id": 22765589,
            "title": "Programmer Ryan Gosling: Legacy",
            "points": 1,
            "user": "thecsw",
            "created_at_i": 1585877335,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://thecsw.github.io/articles/ryan_codes/",
            "domain": "thecsw.github.io"
        },
        {
            "id": 22765583,
            "title": "The End of Civilization and the Real Donald Trump (2016)",
            "points": 2,
            "user": "selimthegrim",
            "created_at_i": 1585877285,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://thehealthcareblog.com/blog/2016/03/15/the-end-of-civilization-and-the-real-donald-trump/",
            "domain": "thehealthcareblog.com"
        },
        {
            "id": 22765581,
            "title": "A Week with Huawei P40 Pro – Early Impressions |TechStomper",
            "points": 1,
            "user": "PrimeVinister",
            "created_at_i": 1585877277,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://techspy.com/news/2336339/a-week-with-huawei-p40-pro-early-impressions-techstomper",
            "domain": "techspy.com"
        },
        {
            "id": 22765576,
            "title": "Potential Wuhan virus vaccine discovered by Pittsburgh scientists",
            "points": 3,
            "user": "briandear",
            "created_at_i": 1585877146,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://nypost.com/2020/04/02/scientists-believe-they-found-potential-coronavirus-vaccine/",
            "domain": "nypost.com"
        },
        {
            "id": 22765571,
            "title": "75 years after he was shot down over Japan, reveals how he survived",
            "points": 1,
            "user": "tomohawk",
            "created_at_i": 1585877044,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://www.washingtonexaminer.com/opinion/special-prisoner",
            "domain": "washingtonexaminer.com"
        },
        {
            "id": 22765535,
            "title": "Amazon sought to divert focus to fired worker amid workplace safety criticism",
            "points": 1,
            "user": "ipsocannibal",
            "created_at_i": 1585876567,
            "time_ago": "an hour ago",
            "comments_count": 2,
            "type": "link",
            "url": "https://www.washingtonpost.com/technology/2020/04/02/amazon-executive-fired-worker/",
            "domain": "washingtonpost.com"
        },
        {
            "id": 22765531,
            "title": "To Make the Perfect Mirror, Physicists Confront the Mystery of Glass",
            "points": 2,
            "user": "sohkamyung",
            "created_at_i": 1585876510,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://www.quantamagazine.org/to-make-the-perfect-mirror-physicists-confront-the-mystery-of-glass-20200402/",
            "domain": "quantamagazine.org"
        },
        {
            "id": 22765522,
            "title": "Simple Word Evaluation in Oil Shell",
            "points": 3,
            "user": "pcr910303",
            "created_at_i": 1585876399,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "http://www.oilshell.org/preview/doc/simple-word-eval.html",
            "domain": "oilshell.org"
        },
        {
            "id": 22765512,
            "title": "Discord used to organize trolling of Zoom AA meetings",
            "points": 4,
            "user": "DaveM_NYIG",
            "created_at_i": 1585876327,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "item?id=22765512"
        },
        {
            "id": 22765510,
            "title": "WFH but Hiring: free marketplace to help talent and employers during Covid-19",
            "points": 2,
            "user": "rafaelc",
            "created_at_i": 1585876292,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://www.wfhbuthiring.com/",
            "domain": "wfhbuthiring.com"
        },
        {
            "id": 22765508,
            "title": "W. H. Auden Was a Messy Roommate",
            "points": 1,
            "user": "vo2maxer",
            "created_at_i": 1585876277,
            "time_ago": "an hour ago",
            "comments_count": 0,
            "type": "link",
            "url": "https://www.theparisreview.org/blog/2020/03/25/w-h-auden-was-a-messy-roommate/",
            "domain": "theparisreview.org"
        }
    ],
    nbPages: 70,
    
};